/**
 * @project LABYRINTH2015
 * ICP project
 * @class Menu
 * @author xsusov01
 * @email  xsusov01@stud.fit.vutbr.cz
 * @author xbandz00
 * @email  xbandz00@stud.fit.vutbr.cz
 * @file menu.cpp
 * @date 2015/05/10
 * @brief main menu widget
*/

#include "menu.h"
#include "widget.h"
#include "ui_menu.h"
#include "loaddialog.h"
#include "startdialogue.h"

#include <iostream>
#include <QApplication>

/**
 * @brief Menu::Menu cosntructor (Generated by Qt)
 * @param parent
 */
Menu::Menu(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::menu)
{
    ui->setupUi(this);
}

/**
 * @brief Menu::~Menu destructor (Generated by Qt)
 */
Menu::~Menu()
{
    delete ui;
}

/**
 * @brief Menu::enable_new_game_button enables "new game" button
 * @
 */
void Menu::enable_new_game_button()
{
    this->ui->new_game->setEnabled(true);
}

/**
 * @brief Menu::disable_new_game_button disables "new game" button
 */
void Menu::disable_new_game_button()
{
    this->ui->new_game->setDisabled(true);
}

/**
 * @brief Menu::on_quit_clicked quits application from main menu
 */
void Menu::on_quit_clicked()
{
    QApplication::quit();
}

/**
 * @brief Menu::on_new_game_clicked calls "new game" dialogue, hides menu
 */
void Menu::on_new_game_clicked()
{
    StartDialogue * new_game_dialogue = new StartDialogue(this);
    this->hide();
    new_game_dialogue->show();
}

/**
 * @brief Menu::on_load_game_clicked calls "load game" dialogue, hides menu
 */
void Menu::on_load_game_clicked()
{
    LoadDialog * load_dialogue = new LoadDialog(this);
    this->hide();
    load_dialogue->show();
}
